name: flutter_study
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  path_provider: ^0.4.0
  shared_preferences: ^0.5.0
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/avatar.jpeg
#  fonts:
#    - family: Raleway
#      fonts:
#        - asset: assets/fonts/Raleway-Regular.ttf
#        - asset: assets/fonts/Raleway-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Raleway-SemiBold.ttf
#          weight: 600
#    - family: AbrilFatface
#      fonts:
#        - asset: assets/fonts/abrilfatface/AbrilFatface-Regular.ttf

